# This file contains values from Cookiecutter

default_context:
  project_name: "quick_capture"
  project_description: "A simple app to add a task/note to a local file"
  organization: "v3services"
  license: "MIT"
  minimal_python_version: "3.10"
  github_name: "martokk"
  email: "25113632+martokk@users.noreply.github.com"
  version: "0.0.1"
  line_length: "100"
  create_example_template: "none"
  create_dockerfile_template: "no"
